version: '3'

services:
  porter-http:
    restart: on-failure
    image: nucypher:latest
    build:
      context: ../../..
      dockerfile: deploy/docker/Dockerfile
    ports:
      # Default Porter port
      - "80:9155"
    volumes:
      - .:/code
      - ~/.local/share/nucypher:/nucypher
    command: ["nucypher", "porter", "run",
              "--provider", "${WEB3_PROVIDER_URI}",
              "--network", "${NUCYPHER_NETWORK}"]

  porter-https:
    restart: on-failure
    image: nucypher:latest
    build:
      context: ../../..
      dockerfile: deploy/docker/Dockerfile
    ports:
      # Default Porter port
      - "443:9155"
    volumes:
      - .:/code
      - ~/.local/share/nucypher:/nucypher
      - "${TLS_DIR}:/etc/porter-tls/"
    command: [ "nucypher", "porter", "run",
               "--provider", "${WEB3_PROVIDER_URI}",
               "--network", "${NUCYPHER_NETWORK}",
               "--tls-key-filepath", "/etc/porter-tls/key.pem",
               "--tls-certificate-filepath", "/etc/porter-tls/cert.pem"]
